name: "hello actions"
description: "this is for greeting someone"
author: "me"

inputs:
  MY_NAME:
    description: "who to greet"
    required: true
    default: world

runs:
  using: "docker"
  image: "Dockerfile"

branding:
  icon: "mic"
  color: "purple"
